# Site settings
title: Peterson Heavy Industries
description: >
  Complicity with coded materials
baseurl: ""
url: "http://millerpeterson.github.io"
github_username:  millerpeterson

# Build settings
markdown: kramdown
